name = "yapayzeka-solution"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[pages_build_config]]
commands = ["npm install", "npm run build"]

[vars]
TELEGRAM_BOT_TOKEN = "8654463682:AAH1i9ZZtvctgE1W_8hLIaBy0KSGyqmatOE"
TELEGRAM_CHAT_ID = "929009215"
